### ISSUE TITLE
the type initializer 'nspector.common.drservicelocator' threw an exception

### ISSUE THREAD

**Issue by AlmightyGagex** [Orbmu2k/nvidiaProfileInspector#116]
I need help with it

**Comment by Lynx-Proxy** [comment]
same here

**Comment by Orbmu2k** [comment]
driver version?

**Comment by Syraun** [comment]
using old version is working, try other versions

**Comment by GregariousJB** [comment]
Same problem here.

![error](https://i.imgur.com/4sJjZqW.png) 

It's an old Lenovo Ideapad Y500 laptop with GT650M's. Driver v 425.31. This only for newer hardware, then?

**Comment by miskfi** [comment]
I have the same problem with GeForce 940MX and driver version 22.21.13.8205. However, version [2.3.0.13](https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.3.0.13) works without any problems.

**Comment by GregariousJB** [comment]
> it makes no sense for supporting very old drivers with the latest versions of inspector. this tool relys heavily on the driver itself. please keep old version of inspector in this case

That's fair. Are you at least willing to include in the Readme which version of Inspector will work for older versions?

**Comment by Orbmu2k** [comment]
> > it makes no sense for supporting very old drivers with the latest versions of inspector. this tool relys heavily on the driver itself. please keep old version of inspector in this case
> 
> That's fair. Are you at least willing to include in the Readme which version of Inspector will work for older versions?

sure iam planning to implement driver version check on startup

**Comment by GregariousJB** [comment]
> > > it makes no sense for supporting very old drivers with the latest versions of inspector. this tool relys heavily on the driver itself. please keep old version of inspector in this case
> > 
> > 
> > That's fair. Are you at least willing to include in the Readme which version of Inspector will work for older versions?
> 
> sure iam planning to implement driver version check on startup

Awesome, thank you 👍

**Comment by Orbmu2k** [comment]
should be fixed in https://github.com/Orbmu2k/nvidiaProfileInspector/releases/tag/2.4.0.4

**Comment by McEagleYT** [comment]
My one doesn't work at all

**Comment by McEagleYT** [comment]
I play on my laptop which graphics are HD family graphics.
I don't have a nvidia graphics card.

**Comment by Stephanov2077** [comment]
Its not fixed yet because Im having the same problem with the newest and older versions, please help me.
Win11, RTX 3090, i5 12400f,16gb ram

**Comment by Noisis** [comment]
can someone help me with this error?
![Screenshot (11)](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/151835466/4d9b8fef-b28c-4146-b2a4-d6e5beac4612)

**Comment by HUSSAINS11** [comment]
I dont know what to do i need help
![Screenshot 2023-11-30 225242](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/152564465/d5a654af-ce51-4feb-9564-734eb38d835c)

**Comment by HUSSAINS11** [comment]
my specs are RTX 3070, Win 11, I7 12700F, 16 gb ram

**Comment by nkiodemfire** [comment]
i also have problems with the latest version  i have an i7 8700 and invidia uhd  630 
![obraz_2023-12-05_205943996](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/71986461/e83e08b7-484f-4838-875b-94b1ba5698b0)

**Comment by stevegiotis** [comment]
i also have the smae problem: 
![image](https://github.com/Orbmu2k/nvidiaProfileInspector/assets/132510262/e8deb148-7436-4346-a6ab-5b1757500ead)

**Comment by Sanrodahood** [comment]
I need help its not working

**Comment by charlie2231** [comment]
I accidentally deleted the Fortnite file from the NVIDIA Profile Inspector

**Comment by charlie2231** [comment]
help

**Comment by giorgi-mxeci** [comment]
anyone got fix for this error?

**Comment by Pablo4304** [comment]
I got the same issue with my lenovo v14 g4 ryzen 5 5500u 8gb ram and radeon grarphics 
![image](https://github.com/user-attachments/assets/adfea311-439f-458b-b3d8-434fa4e55b1d)

**Comment by Milan1022** [comment]
I still have the same problem, someone help me please. My video card is AMD Radeon R5 M430, my processor is G4400

**Comment by R3d-b4** [comment]
![image](https://github.com/user-attachments/assets/3eaaafe6-ed6f-4abd-9752-ee5fcb5665dd)
une exception a été levée par l'initialiseur de type pour 'nspector.Common.DrsSeviceLocator'. pour Nvidia profile inspector

**Comment by gnomforever4fn** [comment]
please upgrade your version of nvidia profile inspector for windows 11

**Comment by hazelxneon** [comment]
AMD can use this ?

**Comment by veskovpro** [comment]
i need help

**Comment by BertJickty** [comment]
I try it to AMD card :)

**Comment by thiastaraperu-cpu** [comment]
ayuden me aparece el mismo error de todos
