### ISSUE TITLE
Comboboxes are not responsive

### ISSUE THREAD

**Issue by akgis32** [Orbmu2k/nvidiaProfileInspector#138]
Hey I always had this wierd issue

That the combo boxes are not responsive it takes 2 click since the first one it rolls down and comes back again, it works only on even clicks

4K 175% scale, Windows 10, Windows 11 doesn't mater

Its fixed by disabling scaling, this doesnt happen in any other program win32 or newer program.
![image](https://user-images.githubusercontent.com/97308113/232354861-bdf4ee6b-fb48-48eb-81f4-44df35f32486.png)

**Comment by d0x360** [comment]
I've had the same issue and I've seen it other places as well...I think it's got something to do with populating the drop down which happens on 1st click... I should have looked at the source before posting lol.

That's an interesting one though.  I've never given it a 2nd thought but I downloaded the source to tweak myself a custom version so I'll check that out and if I find anything I'll post back and also try to get the fix merged if I actually fix it lol

**Comment by akgis32** [comment]
I recently saw there was a new version and it says 

"improved dpi scaling for input dialog"

This is still not fixed. Same behaviour

**Comment by d0x360** [comment]
i had forgotten about this, its on my todo list after i finish some work on an android app that needs some fixes and updates.  shouldnt take me too long...i hope.  Would go faster if the apps original dev hadnt fallen off the planet

**Comment by akgis32** [comment]
Just a frendly bump that this still happens as version 2.4.0.11

**Comment by emoose** [comment]
@akgis32 can you try the 4.2.0.16 release? should hopefully be fixed now

**Comment by akgis32** [comment]
@emoose its fixed on my end 4K 175% scaling win11 23h2

Thanks very much
